// German word bank for the crossword puzzle mode: classic, direct clues
// (not cryptic — see chat decision). Words avoid umlauts/ß for simpler grid
// handling; each entry is { word, clue }.

export const WORD_BANK = [
  { word: "APFEL", clue: "Rundliche Frucht, oft rot oder grün" },
  { word: "BANANE", clue: "Gelbe, gebogene Frucht" },
  { word: "SONNE", clue: "Stern im Zentrum unseres Sonnensystems" },
  { word: "MOND", clue: "Erdtrabant am Nachthimmel" },
  { word: "STERN", clue: "Leuchtender Himmelskörper" },
  { word: "REGEN", clue: "Niederschlag aus Wassertropfen" },
  { word: "SCHNEE", clue: "Weißer Winterniederschlag" },
  { word: "WOLKE", clue: "Schwebendes Gebilde am Himmel" },
  { word: "WASSER", clue: "H2O in flüssiger Form" },
  { word: "FEUER", clue: "Element mit Flammen" },
  { word: "ERDE", clue: "Unser Heimatplanet" },
  { word: "BERG", clue: "Erhebung in der Landschaft" },
  { word: "TAL", clue: "Senke zwischen zwei Bergen" },
  { word: "FLUSS", clue: "Fließendes Gewässer" },
  { word: "MEER", clue: "Große Wassermasse" },
  { word: "STRAND", clue: "Sandiger Küstenabschnitt" },
  { word: "INSEL", clue: "Von Wasser umgebenes Land" },
  { word: "WALD", clue: "Große Ansammlung von Bäumen" },
  { word: "BAUM", clue: "Holzgewächs mit Stamm und Krone" },
  { word: "BLUME", clue: "Pflanze mit Blüte" },
  { word: "GARTEN", clue: "Bepflanztes Grundstück am Haus" },
  { word: "HUND", clue: "Bester Freund des Menschen" },
  { word: "KATZE", clue: "Schnurrendes Haustier" },
  { word: "PFERD", clue: "Reittier mit Mähne" },
  { word: "VOGEL", clue: "Gefiedertes Flugtier" },
  { word: "FISCH", clue: "Tier mit Kiemen und Flossen" },
  { word: "MAUS", clue: "Kleines Nagetier" },
  { word: "BAER", clue: "Großes Waldtier mit dickem Fell" },
  { word: "LOEWE", clue: "König der Tiere" },
  { word: "TIGER", clue: "Gestreifte Raubkatze" },
  { word: "ELEFANT", clue: "Größtes Landsäugetier mit Rüssel" },
  { word: "GIRAFFE", clue: "Tier mit sehr langem Hals" },
  { word: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
  { word: "SCHMETTERLING", clue: "Insekt mit bunten Flügeln" },
  { word: "BIENE", clue: "Honig sammelndes Insekt" },
  { word: "SPINNE", clue: "Achtbeiniges Krabbeltier" },
  { word: "HAUS", clue: "Gebäude zum Wohnen" },
  { word: "FENSTER", clue: "Öffnung in der Wand mit Glas" },
  { word: "TUER", clue: "Öffnung zum Durch- und Zugehen" },
  { word: "TISCH", clue: "Möbelstück zum Essen oder Arbeiten" },
  { word: "STUHL", clue: "Sitzmöbel mit Lehne" },
  { word: "BETT", clue: "Möbel zum Schlafen" },
  { word: "LAMPE", clue: "Gerät zum Beleuchten" },
  { word: "SPIEGEL", clue: "Glas, das Bilder zurückwirft" },
  { word: "UHR", clue: "Gerät zur Zeitanzeige" },
  { word: "BUCH", clue: "Gebundene Sammlung bedruckter Seiten" },
  { word: "STIFT", clue: "Gerät zum Schreiben" },
  { word: "PAPIER", clue: "Material zum Beschreiben und Drucken" },
  { word: "BRIEF", clue: "Schriftliche Mitteilung per Post" },
  { word: "TELEFON", clue: "Gerät zum Anrufen" },
  { word: "COMPUTER", clue: "Elektronisches Rechengerät" },
  { word: "TASTATUR", clue: "Eingabegerät mit vielen Tasten" },
  { word: "BILDSCHIRM", clue: "Anzeigegerät eines Computers" },
  { word: "AUTO", clue: "Kraftfahrzeug auf vier Rädern" },
  { word: "ZUG", clue: "Fahrzeug auf Schienen" },
  { word: "SCHIFF", clue: "Fahrzeug auf dem Wasser" },
  { word: "FLUGZEUG", clue: "Fahrzeug in der Luft" },
  { word: "FAHRRAD", clue: "Zweirädriges Fahrzeug mit Pedalen" },
  { word: "STRASSE", clue: "Weg für Fahrzeuge" },
  { word: "BRUECKE", clue: "Bauwerk über ein Hindernis" },
  { word: "STADT", clue: "Großer, dicht besiedelter Ort" },
  { word: "DORF", clue: "Kleine ländliche Siedlung" },
  { word: "LAND", clue: "Staat oder Gebiet" },
  { word: "KUECHE", clue: "Raum zum Kochen" },
  { word: "BROT", clue: "Gebackenes Grundnahrungsmittel" },
  { word: "BUTTER", clue: "Streichfett aus Milch" },
  { word: "KAESE", clue: "Milchprodukt zum Aufschneiden" },
  { word: "MILCH", clue: "Weißes Getränk von der Kuh" },
  { word: "KAFFEE", clue: "Anregendes Heißgetränk" },
  { word: "TEE", clue: "Aufgussgetränk aus Blättern" },
  { word: "ZUCKER", clue: "Süßender weißer Stoff" },
  { word: "SALZ", clue: "Würzendes Mineral" },
  { word: "SUPPE", clue: "Flüssiges Gericht" },
  { word: "KUCHEN", clue: "Süßes Gebäck zum Kaffee" },
  { word: "SCHOKOLADE", clue: "Süßigkeit aus Kakao" },
  { word: "EIS", clue: "Gefrorene Süßspeise" },
  { word: "MUSIK", clue: "Kunst der geordneten Klänge" },
  { word: "GITARRE", clue: "Zupfinstrument mit Saiten" },
  { word: "KLAVIER", clue: "Tasteninstrument" },
  { word: "TROMMEL", clue: "Schlaginstrument" },
  { word: "FILM", clue: "Bewegtes Bildwerk im Kino" },
  { word: "THEATER", clue: "Ort für Bühnenaufführungen" },
  { word: "SPORT", clue: "Körperliche Betätigung im Wettkampf" },
  { word: "FUSSBALL", clue: "Ballsport mit elf Spielern pro Team" },
  { word: "TENNIS", clue: "Schlägersport mit Netz" },
  { word: "SCHWIMMEN", clue: "Fortbewegung im Wasser" },
  { word: "WINTER", clue: "Kalte Jahreszeit" },
  { word: "SOMMER", clue: "Warme Jahreszeit" },
  { word: "HERBST", clue: "Jahreszeit mit fallendem Laub" },
  { word: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
  { word: "MONTAG", clue: "Erster Wochentag" },
  { word: "FREITAG", clue: "Letzter Arbeitstag der Woche" },
  { word: "SCHULE", clue: "Ort des Lernens für Kinder" },
  { word: "LEHRER", clue: "Person, die unterrichtet" },
  { word: "ARZT", clue: "Person, die Kranke behandelt" },
  { word: "KOCH", clue: "Person, die beruflich kocht" },
  { word: "BAECKER", clue: "Person, die Brot backt" },
  { word: "POLIZEI", clue: "Ordnungshüter des Staates" },
  { word: "FEUERWEHR", clue: "Rettungsdienst bei Bränden" },
  { word: "KOENIG", clue: "Männliches Staatsoberhaupt einer Monarchie" },
  { word: "SCHLOSS", clue: "Herrschaftliches Gebäude oder Sicherung an der Tür" },
  { word: "TURM", clue: "Hoch aufragendes, schmales Bauwerk" },
  { word: "RING", clue: "Rundes Schmuckstück für den Finger" },
  { word: "KRONE", clue: "Kopfschmuck eines Herrschers" },
  { word: "SCHWERT", clue: "Klingenwaffe des Mittelalters" },
  { word: "DRACHE", clue: "Feuerspeiendes Fabelwesen" },
  { word: "PIRAT", clue: "Seeräuber" },
  { word: "SCHATZ", clue: "Verborgener Reichtum" },
  { word: "KARTE", clue: "Darstellung von Land auf Papier, oder Spielkarte" },
  { word: "KOMPASS", clue: "Gerät zur Richtungsbestimmung" },
  { word: "ZELT", clue: "Mobile Unterkunft aus Stoff" },
  { word: "RUCKSACK", clue: "Tragetasche für den Rücken" },
  { word: "SEIL", clue: "Dickes, geflochtenes Tau" },
  { word: "FEDER", clue: "Leichtes Vogelteil, auch zum Schreiben" },
  { word: "GLAS", clue: "Durchsichtiges Trinkgefäß" },
  { word: "FLASCHE", clue: "Behälter für Flüssigkeiten mit engem Hals" },
  { word: "TELLER", clue: "Flaches Geschirr zum Essen" },
  { word: "LOEFFEL", clue: "Besteckteil zum Schöpfen" },
  { word: "GABEL", clue: "Besteckteil mit Zinken" },
  { word: "MESSER", clue: "Schneidendes Besteckteil" },
  { word: "SCHERE", clue: "Werkzeug zum Schneiden mit zwei Klingen" },
  { word: "HAMMER", clue: "Werkzeug zum Einschlagen von Nägeln" },
  { word: "NAGEL", clue: "Metallstift zum Befestigen" },
  { word: "SCHRAUBE", clue: "Gewindestift zum Befestigen" },
  { word: "LEITER", clue: "Gerät zum Erklimmen von Höhen" },
  { word: "EIMER", clue: "Behälter mit Henkel für Wasser" },
  { word: "BESEN", clue: "Gerät zum Kehren" },
  { word: "KISSEN", clue: "Weiches Polster zum Anlehnen" },
  { word: "DECKE", clue: "Textil zum Zudecken, oder oberer Raumabschluss" },
  { word: "TEPPICH", clue: "Bodenbelag aus Textil" },
  { word: "VORHANG", clue: "Textil vor dem Fenster" },
  { word: "SCHRANK", clue: "Möbel zum Verstauen von Kleidung" },
  { word: "REGAL", clue: "Möbel mit Fächern oder Brettern" },
  { word: "KERZE", clue: "Wachslicht mit Docht" },
  { word: "FAHNE", clue: "Stofftuch als Landessymbol" },
  { word: "MEDAILLE", clue: "Auszeichnung für Sportler" },
  { word: "POKAL", clue: "Trophäe für Sieger" },
  { word: "GESCHENK", clue: "Etwas, das man verschenkt" },
  { word: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
  { word: "FEIER", clue: "Festliches Beisammensein" },
  { word: "MUSEUM", clue: "Ort zur Ausstellung von Kunst oder Geschichte" },
  { word: "BIBLIOTHEK", clue: "Ort mit vielen Büchern zum Ausleihen" },
  { word: "MARKT", clue: "Ort zum Kaufen und Verkaufen" },
  { word: "LADEN", clue: "Geschäft zum Einkaufen" },
  { word: "GELD", clue: "Zahlungsmittel" },
  { word: "MUENZE", clue: "Rundes Metallgeldstück" },
  { word: "SCHEIN", clue: "Papiergeldstück" },
];
