// German word bank for the crossword puzzle mode: classic (non-cryptic)
// clues, but pitched at a more challenging, adult general-knowledge level
// rather than simple object descriptions. Words avoid umlauts/ß for
// simpler grid handling; each entry is { word, clue }.

export const WORD_BANK = [
  { word: "BERLIN", clue: "Hauptstadt Deutschlands" },
  { word: "PARIS", clue: "Hauptstadt Frankreichs" },
  { word: "MADRID", clue: "Hauptstadt Spaniens" },
  { word: "CANBERRA", clue: "Hauptstadt Australiens" },
  { word: "OTTAWA", clue: "Hauptstadt Kanadas" },
  { word: "LISSABON", clue: "Hauptstadt Portugals" },
  { word: "ATHEN", clue: "Hauptstadt Griechenlands, Wiege der Demokratie" },
  { word: "KAIRO", clue: "Hauptstadt Ägyptens am Nil" },
  { word: "DONAU", clue: "Zweitlängster Fluss Europas" },
  { word: "RHEIN", clue: "Fluss, der durch Basel, Köln und Rotterdam fließt" },
  { word: "ALPEN", clue: "Höchstes Gebirge Europas" },
  { word: "SAHARA", clue: "Größte Wüste der Welt" },
  { word: "AMAZONAS", clue: "Wasserreichster Fluss der Erde" },
  { word: "EVEREST", clue: "Höchster Berg der Welt" },
  { word: "PAZIFIK", clue: "Größter Ozean der Erde" },
  { word: "ANTARKTIS", clue: "Kontinent rund um den Südpol" },
  { word: "GALAXIE", clue: "Riesige Ansammlung von Sternen im All" },
  { word: "PLANET", clue: "Himmelskörper, der einen Stern umkreist" },
  { word: "JUPITER", clue: "Größter Planet unseres Sonnensystems" },
  { word: "MERKUR", clue: "Sonnennächster Planet" },
  { word: "GALILEI", clue: "Astronom, der die Jupitermonde entdeckte" },
  { word: "EINSTEIN", clue: "Physiker der Relativitätstheorie" },
  { word: "NEWTON", clue: "Namensgeber des Gravitationsgesetzes" },
  { word: "DARWIN", clue: "Begründer der Evolutionstheorie" },
  { word: "MOZART", clue: "Salzburger Komponist der Klassik" },
  { word: "BEETHOVEN", clue: "Tauber Komponist der Neunten Sinfonie" },
  { word: "GOETHE", clue: "Dichter des Faust" },
  { word: "SCHILLER", clue: "Dichter von Wilhelm Tell" },
  { word: "KAFKA", clue: "Prager Autor der Verwandlung" },
  { word: "SHAKESPEARE", clue: "Englischer Dramatiker aus Stratford" },
  { word: "PICASSO", clue: "Maler des Kubismus aus Spanien" },
  { word: "GUTENBERG", clue: "Erfinder des Buchdrucks" },
  { word: "PHARAO", clue: "Herrschertitel im alten Ägypten" },
  { word: "PYRAMIDE", clue: "Grabbauwerk der Pharaonen" },
  { word: "GLADIATOR", clue: "Kämpfer in der römischen Arena" },
  { word: "KOLOSSEUM", clue: "Antikes Amphitheater in Rom" },
  { word: "LEGION", clue: "Militärische Einheit im alten Rom" },
  { word: "IMPERIUM", clue: "Großes Herrschaftsgebiet, etwa das römische" },
  { word: "REPUBLIK", clue: "Staatsform ohne Monarchen" },
  { word: "DEMOKRATIE", clue: "Herrschaftsform des Volkes" },
  { word: "REVOLUTION", clue: "Grundlegender politischer Umsturz" },
  { word: "DIPLOMAT", clue: "Vertreter eines Staates im Ausland" },
  { word: "VERFASSUNG", clue: "Grundgesetzliches Regelwerk eines Staates" },
  { word: "PARLAMENT", clue: "Gesetzgebende Volksvertretung" },
  { word: "KANZLERIN", clue: "Weibliche Regierungschefin in Deutschland" },
  { word: "MONARCHIE", clue: "Staatsform mit erblichem Oberhaupt" },
  { word: "ATOM", clue: "Kleinster Baustein der Materie" },
  { word: "MOLEKUEL", clue: "Verbindung mehrerer Atome" },
  { word: "ELEMENT", clue: "Grundstoff im Periodensystem" },
  { word: "SAUERSTOFF", clue: "Lebenswichtiges Gas zum Atmen" },
  { word: "WASSERSTOFF", clue: "Leichtestes chemisches Element" },
  { word: "KOHLENSTOFF", clue: "Element, aus dem Diamant besteht" },
  { word: "GRAVITATION", clue: "Kraft, die Dinge zu Boden zieht" },
  { word: "ENERGIE", clue: "Physikalische Fähigkeit, Arbeit zu verrichten" },
  { word: "MAGNET", clue: "Objekt, das Eisen anzieht" },
  { word: "VULKAN", clue: "Berg, der Lava ausstößt" },
  { word: "ERDBEBEN", clue: "Plötzliche Erschütterung der Erdkruste" },
  { word: "GLETSCHER", clue: "Langsam fließende Eismasse im Gebirge" },
  { word: "OASE", clue: "Fruchtbare Wasserstelle in der Wüste" },
  { word: "TUNDRA", clue: "Baumlose Kältesteppe im hohen Norden" },
  { word: "DSCHUNGEL", clue: "Dichter tropischer Regenwald" },
  { word: "SAVANNE", clue: "Grasland mit vereinzelten Bäumen in Afrika" },
  { word: "FJORD", clue: "Schmale Meeresbucht in Skandinavien" },
  { word: "GEYSIR", clue: "Heiße Quelle, die periodisch Wasser ausstößt" },
  { word: "MERIDIAN", clue: "Gedachter Längenkreis auf der Erdkugel" },
  { word: "KONTINENT", clue: "Großer zusammenhängender Erdteil" },
  { word: "HALBINSEL", clue: "Landstück, das nur an einer Seite ans Meer grenzt" },
  { word: "ARCHIPEL", clue: "Gruppe eng beieinanderliegender Inseln" },
  { word: "METROPOLE", clue: "Bedeutende Großstadt" },
  { word: "NOMADE", clue: "Mensch ohne festen Wohnsitz" },
  { word: "KARAWANE", clue: "Reisegruppe durch die Wüste, oft mit Kamelen" },
  { word: "KOLONIE", clue: "Von einer fremden Macht beherrschtes Gebiet" },
  { word: "MYTHOLOGIE", clue: "Sammlung von Göttersagen eines Volkes" },
  { word: "ORAKEL", clue: "Antike Weissagungsstätte, etwa in Delphi" },
  { word: "SPHINX", clue: "Mischwesen mit Löwenkörper und Menschenkopf" },
  { word: "ODYSSEE", clue: "Homers Epos über eine lange Irrfahrt" },
  { word: "ILIAS", clue: "Homers Epos über den Krieg um Troja" },
  { word: "TROJA", clue: "Antike Stadt, berühmt durch ein hölzernes Pferd" },
  { word: "OLYMP", clue: "Sitz der griechischen Götter" },
  { word: "ZEUS", clue: "Oberster Gott der griechischen Mythologie" },
  { word: "POSEIDON", clue: "Griechischer Gott des Meeres" },
  { word: "ATHENE", clue: "Griechische Göttin der Weisheit" },
  { word: "PROMETHEUS", clue: "Titan, der den Menschen das Feuer brachte" },
  { word: "LABYRINTH", clue: "Verwirrendes Wegesystem mit vielen Sackgassen" },
  { word: "ALCHEMIE", clue: "Mittelalterliche Vorstufe der Chemie" },
  { word: "TELESKOP", clue: "Optisches Gerät zur Himmelsbeobachtung" },
  { word: "MIKROSKOP", clue: "Gerät zur Vergrößerung kleinster Objekte" },
  { word: "KOMPASS", clue: "Navigationsgerät mit magnetischer Nadel" },
  { word: "SEXTANT", clue: "Historisches Gerät zur Standortbestimmung auf See" },
  { word: "PENDEL", clue: "Physikalisches Objekt, das gleichmäßig schwingt" },
  { word: "PRISMA", clue: "Optisches Element, das Licht in Farben zerlegt" },
  { word: "SPEKTRUM", clue: "Zerlegtes Farbband des Lichts" },
  { word: "GENOM", clue: "Gesamte Erbinformation eines Lebewesens" },
  { word: "BAKTERIUM", clue: "Einzelliger Mikroorganismus" },
  { word: "VIRUS", clue: "Winziger Krankheitserreger ohne eigenen Stoffwechsel" },
  { word: "IMMUNSYSTEM", clue: "Körpereigene Abwehr gegen Krankheiten" },
  { word: "OEKOSYSTEM", clue: "Lebensgemeinschaft aus Organismen und Umwelt" },
  { word: "SYMBIOSE", clue: "Enges Zusammenleben zweier Arten zum beiderseitigen Nutzen" },
  { word: "MIGRATION", clue: "Wanderung von Tieren oder Menschen" },
  { word: "EPIDEMIE", clue: "Zeitlich begrenzte Ausbreitung einer Krankheit" },
  { word: "PANDEMIE", clue: "Weltweite Ausbreitung einer Krankheit" },
  { word: "ANTIBIOTIKUM", clue: "Medikament gegen bakterielle Infektionen" },
  { word: "DIAGNOSE", clue: "Ärztliche Feststellung einer Krankheit" },
  { word: "CHIRURG", clue: "Arzt, der operiert" },
  { word: "PSYCHOLOGIE", clue: "Wissenschaft vom menschlichen Erleben und Verhalten" },
  { word: "PHILOSOPHIE", clue: "Wissenschaft von den Grundfragen des Seins" },
  { word: "SOKRATES", clue: "Griechischer Philosoph, Lehrer Platons" },
  { word: "PLATON", clue: "Philosoph, der die Ideenlehre begründete" },
  { word: "ARISTOTELES", clue: "Schüler Platons und Lehrer Alexanders des Großen" },
  { word: "KANT", clue: "Königsberger Philosoph der Aufklärung" },
  { word: "NIETZSCHE", clue: "Philosoph, der Also sprach Zarathustra schrieb" },
  { word: "UTOPIE", clue: "Idealvorstellung einer nicht existierenden Gesellschaft" },
  { word: "IDEOLOGIE", clue: "System politischer oder gesellschaftlicher Grundüberzeugungen" },
  { word: "ETHIK", clue: "Lehre vom moralisch richtigen Handeln" },
  { word: "PARADOXON", clue: "Scheinbar widersprüchliche, aber wahre Aussage" },
  { word: "METAPHER", clue: "Sprachliches Bild, das einen Begriff durch einen anderen ersetzt" },
  { word: "SONETT", clue: "Gedichtform mit vierzehn Zeilen" },
  { word: "TRAGOEDIE", clue: "Dramatisches Werk mit unglücklichem Ausgang" },
  { word: "KOMOEDIE", clue: "Heiteres Bühnenstück mit gutem Ausgang" },
  { word: "SATIRE", clue: "Literarische Form, die Missstände spöttisch bloßstellt" },
  { word: "ALLEGORIE", clue: "Bildliche Darstellung eines abstrakten Begriffs" },
  { word: "MANUSKRIPT", clue: "Handschriftlicher oder ungedruckter Text" },
  { word: "PLAGIAT", clue: "Unrechtmäßige Übernahme fremden geistigen Eigentums" },
  { word: "ZENSUR", clue: "Staatliche Kontrolle und Unterdrückung von Inhalten" },
  { word: "PROPAGANDA", clue: "Gezielte, oft einseitige Beeinflussung der Meinung" },
  { word: "SYMPHONIE", clue: "Mehrsätziges Orchesterwerk" },
  { word: "LIBRETTO", clue: "Textbuch einer Oper" },
  { word: "DIRIGENT", clue: "Leiter eines Orchesters" },
  { word: "VIRTUOSE", clue: "Meisterhafter Künstler seines Fachs" },
  { word: "RENAISSANCE", clue: "Kulturelle Wiedergeburt der Antike ab dem 14. Jahrhundert" },
  { word: "BAROCK", clue: "Üppiger Kunststil des 17. Jahrhunderts" },
  { word: "IMPRESSIONISMUS", clue: "Kunstrichtung, die flüchtige Lichteindrücke einfängt" },
  { word: "SURREALISMUS", clue: "Kunstrichtung des Traumhaften und Unwirklichen" },
  { word: "FRESKO", clue: "Wandmalerei auf frischem Kalkputz" },
  { word: "MOSAIK", clue: "Bild aus vielen kleinen, zusammengesetzten Steinchen" },
  { word: "SKULPTUR", clue: "Dreidimensionales Kunstwerk, oft aus Stein oder Bronze" },
  { word: "ARCHITEKT", clue: "Person, die Gebäude entwirft" },
  { word: "KATHEDRALE", clue: "Große bischöfliche Kirche" },
  { word: "MINARETT", clue: "Turm einer Moschee" },
  { word: "PAGODE", clue: "Mehrstöckiger Tempelturm in Ostasien" },
  { word: "KATAKOMBE", clue: "Unterirdische Grabanlage" },
  { word: "MAUSOLEUM", clue: "Prunkvolles Grabmal" },
  { word: "OBELISK", clue: "Hoher, spitz zulaufender Steinpfeiler" },
  { word: "HIEROGLYPHE", clue: "Bildzeichen der altägyptischen Schrift" },
  { word: "PAPYRUS", clue: "Beschreibstoff des alten Ägypten" },
  { word: "AMPHORE", clue: "Antikes Gefäß mit zwei Henkeln" },
  { word: "DYNASTIE", clue: "Herrscherfolge innerhalb einer Familie" },
  { word: "MONOPOL", clue: "Alleinherrschaft eines Anbieters über einen Markt" },
  { word: "INFLATION", clue: "Anhaltender Anstieg des allgemeinen Preisniveaus" },
  { word: "REZESSION", clue: "Wirtschaftlicher Abschwung" },
  { word: "BOERSE", clue: "Markt für den Handel mit Wertpapieren" },
  { word: "WAEHRUNG", clue: "Gesetzliches Zahlungsmittel eines Landes" },
  { word: "EXPORT", clue: "Ausfuhr von Waren ins Ausland" },
  { word: "GLOBALISIERUNG", clue: "Zunehmende weltweite Vernetzung von Wirtschaft und Kultur" },
  { word: "URBANISIERUNG", clue: "Zunehmende Verstädterung einer Gesellschaft" },
  { word: "DEMOGRAFIE", clue: "Wissenschaft von der Bevölkerungsstruktur" },
  { word: "ARCHAEOLOGE", clue: "Wissenschaftler, der Ausgrabungen erforscht" },
  { word: "METEOROLOGE", clue: "Wissenschaftler, der das Wetter erforscht" },
  { word: "ASTRONAUT", clue: "Person, die ins Weltall reist" },
  { word: "KOSMONAUT", clue: "Russische Bezeichnung für Raumfahrer" },
  { word: "SATELLIT", clue: "Künstlicher Himmelskörper im Erdorbit" },
  { word: "RAKETE", clue: "Fahrzeug zum Start ins Weltall" },
  { word: "ORBIT", clue: "Umlaufbahn eines Himmelskörpers" },
  { word: "SCHWERELOSIGKEIT", clue: "Zustand ohne spürbare Gravitation" },
  { word: "ANTARKTIKA", clue: "Anderer Name für den Südpolarkontinent" },
  { word: "GROENLAND", clue: "Größte Insel der Welt" },
  { word: "ISLAND", clue: "Vulkaninsel im Nordatlantik" },
  { word: "SIZILIEN", clue: "Größte Insel im Mittelmeer" },
  { word: "SARDINIEN", clue: "Zweitgrößte Mittelmeerinsel" },
  { word: "KORSIKA", clue: "Geburtsinsel Napoleons" },
  { word: "PYRENAEEN", clue: "Gebirge zwischen Frankreich und Spanien" },
  { word: "ANDEN", clue: "Längstes Gebirge der Welt in Südamerika" },
  { word: "KILIMANDSCHARO", clue: "Höchster Berg Afrikas" },
  { word: "MISSISSIPPI", clue: "Großer Strom in Nordamerika" },
  { word: "GANGES", clue: "Heiliger Fluss in Indien" },
  { word: "JANGTSE", clue: "Längster Fluss Asiens" },
  { word: "WOLGA", clue: "Längster Fluss Europas" },
  { word: "ELBE", clue: "Fluss durch Hamburg und Dresden" },
  { word: "OSTSEE", clue: "Binnenmeer nördlich von Deutschland" },
  { word: "TOTESMEER", clue: "Salzsee zwischen Israel und Jordanien" },
  { word: "GALAPAGOS", clue: "Inselgruppe, die Darwin inspirierte" },
  { word: "MADAGASKAR", clue: "Große Insel vor Ostafrika" },
  { word: "PATAGONIEN", clue: "Region am südlichen Ende Südamerikas" },
  { word: "SERENGETI", clue: "Weites Grasland-Nationalpark in Tansania" },
  { word: "MEKONG", clue: "Großer Fluss in Südostasien" },
  { word: "EUPHRAT", clue: "Fluss durch das alte Mesopotamien" },
  { word: "MESOPOTAMIEN", clue: "Zweistromland zwischen Euphrat und Tigris" },
  { word: "BABYLON", clue: "Antike Stadt mit hängenden Gärten" },
  { word: "SUMERER", clue: "Frühes Volk Mesopotamiens, erfand die Keilschrift" },
  { word: "KEILSCHRIFT", clue: "Älteste bekannte Schriftform" },
  { word: "TERRAKOTTA", clue: "Gebrannter Ton, berühmt durch chinesische Armee" },
  { word: "MUMIE", clue: "Konservierter Leichnam im alten Ägypten" },
  { word: "SARKOPHAG", clue: "Steinerner Sarg der Antike" },
  { word: "ANUBIS", clue: "Ägyptischer Gott mit Schakalkopf" },
  { word: "OSIRIS", clue: "Ägyptischer Gott der Totenwelt" },
  { word: "TUTANCHAMUN", clue: "Jung verstorbener ägyptischer Pharao" },
  { word: "KLEOPATRA", clue: "Letzte Pharaonin Ägyptens" },
  { word: "AUGUSTUS", clue: "Erster römischer Kaiser" },
  { word: "SPARTACUS", clue: "Gladiator, der einen Sklavenaufstand anführte" },
  { word: "HANNIBAL", clue: "Feldherr, der mit Elefanten die Alpen überquerte" },
  { word: "KARTHAGO", clue: "Antike Stadt, Roms großer Rivale" },
  { word: "SPARTA", clue: "Antike griechische Kriegerstadt" },
  { word: "MARATHON", clue: "Antike Schlacht, Namensgeber eines Laufs" },
  { word: "AKROPOLIS", clue: "Antike Tempelburg über Athen" },
  { word: "PARTHENON", clue: "Haupttempel auf der Akropolis" },
  { word: "AGORA", clue: "Marktplatz im antiken Griechenland" },
  { word: "STOA", clue: "Antike Säulenhalle, auch Philosophenschule" },
  { word: "TRIUMPHBOGEN", clue: "Ehrentor für siegreiche Feldherren" },
  { word: "FORUM", clue: "Öffentlicher Platz im alten Rom" },
  { word: "SENAT", clue: "Beratendes Gremium im alten Rom" },
  { word: "VESUV", clue: "Vulkan, der Pompeji verschüttete" },
  { word: "POMPEJI", clue: "Römische Stadt, unter Asche konserviert" },
  { word: "ETNA", clue: "Aktiver Vulkan auf Sizilien" },
  { word: "TSUNAMI", clue: "Durch Erdbeben ausgelöste Flutwelle" },
  { word: "MONSUN", clue: "Jahreszeitlich wechselnder Wind in Asien" },
  { word: "PASSAT", clue: "Beständiger tropischer Ostwind" },
  { word: "TORNADO", clue: "Trichterförmiger Wirbelsturm" },
  { word: "HURRIKAN", clue: "Tropischer Wirbelsturm im Atlantik" },
  { word: "TAIFUN", clue: "Tropischer Wirbelsturm im Pazifik" },
  { word: "POLARLICHT", clue: "Leuchterscheinung am Nachthimmel der Polarregionen" },
  { word: "SUPERNOVA", clue: "Gewaltige Explosion am Ende eines Sternenlebens" },
  { word: "URKNALL", clue: "Theorie vom Beginn des Universums" },
  { word: "ASTEROID", clue: "Kleiner Himmelskörper zwischen Mars und Jupiter" },
  { word: "KOMET", clue: "Himmelskörper mit charakteristischem Schweif" },
  { word: "METEORIT", clue: "Auf der Erde eingeschlagener Himmelskörper" },
  { word: "LICHTJAHR", clue: "Entfernungseinheit in der Astronomie" },
  { word: "THERMODYNAMIK", clue: "Physik der Wärme und Energieumwandlung" },
  { word: "OPTIK", clue: "Physikalische Lehre vom Licht" },
  { word: "AKUSTIK", clue: "Physikalische Lehre vom Schall" },
  { word: "ISOTOP", clue: "Atomvariante mit gleicher Protonenzahl" },
  { word: "KATALYSATOR", clue: "Stoff, der eine Reaktion beschleunigt" },
  { word: "ENZYM", clue: "Biologischer Katalysator im Körper" },
  { word: "CHROMOSOM", clue: "Träger der Erbinformation im Zellkern" },
  { word: "MUTATION", clue: "Veränderung im Erbgut" },
  { word: "FOSSIL", clue: "Versteinerter Überrest eines Lebewesens" },
  { word: "DINOSAURIER", clue: "Ausgestorbene Riesenechse" },
  { word: "MAMMUT", clue: "Ausgestorbener Verwandter des Elefanten" },
  { word: "NEANDERTALER", clue: "Ausgestorbene Menschenart" },
  { word: "EISZEIT", clue: "Kalte Klimaepoche mit ausgedehnten Gletschern" },
  { word: "TEKTONIK", clue: "Lehre von den Bewegungen der Erdplatten" },
  { word: "MAGMA", clue: "Geschmolzenes Gestein im Erdinneren" },
  { word: "LAVA", clue: "An die Oberfläche getretenes Magma" },
  { word: "GRANIT", clue: "Hartes, kristallines Gestein" },
  { word: "BERNSTEIN", clue: "Fossiles Baumharz, oft mit Einschlüssen" },
  { word: "MARMOR", clue: "Edles Gestein für Skulpturen" },
  { word: "OBSIDIAN", clue: "Vulkanisches Glasgestein" },
  { word: "DIAMANT", clue: "Härtestes natürliches Mineral" },
  { word: "SMARAGD", clue: "Grüner Edelstein" },
  { word: "RUBIN", clue: "Roter Edelstein" },
  { word: "SAPHIR", clue: "Blauer Edelstein" },
  { word: "TOPAS", clue: "Edelstein in vielen Farbvarianten" },
  { word: "OPAL", clue: "Edelstein mit schillerndem Farbenspiel" },
  { word: "PERLE", clue: "Organischer Schmuckstein aus Muscheln" },
  { word: "PLANKTON", clue: "Schwebende Kleinstlebewesen im Wasser" },
  { word: "MANGROVE", clue: "Salzwassertolerantes Küstengehölz" },
  { word: "PRAERIE", clue: "Nordamerikanisches Grasland" },
  { word: "TAIGA", clue: "Nadelwaldgürtel der nördlichen Erde" },
  { word: "PERMAFROST", clue: "Dauerhaft gefrorener Boden" },
  { word: "LAWINE", clue: "Abgehende Schnee- oder Eismasse am Berg" },
  { word: "GEZEITEN", clue: "Regelmäßiges Steigen und Fallen des Meeresspiegels" },
  { word: "GOLFSTROM", clue: "Warme Meeresströmung im Atlantik" },
  { word: "GREENWICH", clue: "Ort des Nullmeridians bei London" },
  { word: "ZEITZONE", clue: "Gebiet mit einheitlicher Uhrzeit" },
  { word: "KARAVELLE", clue: "Segelschiff der Entdeckerzeit" },
  { word: "GALEONE", clue: "Großes Segelschiff des 16. Jahrhunderts" },
  { word: "MAGELLAN", clue: "Seefahrer, dessen Expedition die Erde umrundete" },
  { word: "KOLUMBUS", clue: "Entdecker, der 1492 Amerika erreichte" },
  { word: "MARCOPOLO", clue: "Venezianischer Reisender nach China" },
  { word: "INKA", clue: "Altes Andenvolk, erbaute Machu Picchu" },
  { word: "MAYA", clue: "Altes Volk Mittelamerikas mit eigenem Kalender" },
  { word: "AZTEKEN", clue: "Altes Volk im heutigen Mexiko" },
  { word: "MACHUPICCHU", clue: "Verlorene Stadt der Inka in den Anden" },
  { word: "STONEHENGE", clue: "Steinkreis-Monument in England" },
  { word: "WIKINGER", clue: "Seefahrendes Volk aus Skandinavien" },
  { word: "RUNEN", clue: "Altes germanisches Schriftzeichen" },
  { word: "KELTEN", clue: "Altes Volk in weiten Teilen Europas" },
  { word: "GALLIEN", clue: "Römischer Name für das alte Frankreich" },
  { word: "HUNNEN", clue: "Reiternomadenvolk unter Attila" },
  { word: "ATTILA", clue: "Gefürchteter Anführer der Hunnen" },
  { word: "KREUZZUG", clue: "Mittelalterlicher Feldzug ins Heilige Land" },
  { word: "RITTER", clue: "Berittener Kämpfer des Mittelalters" },
  { word: "TURNIER", clue: "Ritterlicher Zweikampfwettbewerb" },
  { word: "ZUNFT", clue: "Mittelalterliche Handwerkervereinigung" },
  { word: "HANSE", clue: "Mittelalterlicher Handelsbund norddeutscher Städte" },
  { word: "PEST", clue: "Verheerende mittelalterliche Seuche" },
  { word: "INQUISITION", clue: "Kirchliches Gericht gegen Ketzerei" },
  { word: "REFORMATION", clue: "Kirchliche Erneuerungsbewegung Luthers" },
  { word: "ABLASS", clue: "Kirchlicher Erlass von Sündenstrafen" },
  { word: "HUGENOTTEN", clue: "Verfolgte französische Protestanten" },
  { word: "ABSOLUTISMUS", clue: "Herrschaftsform uneingeschränkter Königsmacht" },
  { word: "GUILLOTINE", clue: "Hinrichtungsgerät der Französischen Revolution" },
  { word: "BASTILLE", clue: "Pariser Gefängnis, gestürmt 1789" },
  { word: "NAPOLEON", clue: "Französischer Kaiser, unterlag bei Waterloo" },
  { word: "WATERLOO", clue: "Schlacht, die Napoleons Herrschaft beendete" },
  { word: "KOLONIALISMUS", clue: "Politik der Beherrschung fremder Gebiete" },
  { word: "SKLAVEREI", clue: "Historisches System der Zwangsarbeit" },
  { word: "BUERGERKRIEG", clue: "Krieg zwischen Gruppen desselben Staates" },
  { word: "WELTKRIEG", clue: "Globaler bewaffneter Konflikt" },
  { word: "KALTERKRIEG", clue: "Politische Blockkonfrontation ohne offenen Krieg" },
  { word: "MAUERFALL", clue: "Ereignis 1989 in Berlin" },
  { word: "NOBELPREIS", clue: "Hohe internationale Auszeichnung" },
  { word: "OLYMPIADE", clue: "Alle vier Jahre stattfindender Sportwettkampf" },
  { word: "DEKATHLON", clue: "Zehnkampf der Leichtathletik" },
  { word: "SCHACHMATT", clue: "Endzustand eines Schachspiels" },
  { word: "BOXRING", clue: "Kampfstätte für Boxer" },
  { word: "REGATTA", clue: "Segel- oder Ruderwettfahrt" },
  { word: "BIATHLON", clue: "Wintersport aus Skilanglauf und Schießen" },
  { word: "SLALOM", clue: "Skirennen mit engen Torkombinationen" },
  { word: "ABSEITS", clue: "Regelverstoß im Fußball" },
  { word: "SCHIEDSRICHTER", clue: "Person, die ein Sportspiel leitet" },
  { word: "STADION", clue: "Große Sportarena für Zuschauer" },
  { word: "MASKOTTCHEN", clue: "Glücksbringer-Figur einer Veranstaltung" },
  { word: "STREICHQUARTETT", clue: "Kammermusikbesetzung mit vier Streichern" },
  { word: "KONTRABASS", clue: "Größtes und tiefstes Streichinstrument" },
  { word: "FAGOTT", clue: "Tiefes Holzblasinstrument" },
  { word: "OBOE", clue: "Doppelrohrblatt-Holzblasinstrument" },
  { word: "POSAUNE", clue: "Blechblasinstrument mit Zug" },
  { word: "XYLOFON", clue: "Schlaginstrument mit Holzstäben" },
  { word: "CEMBALO", clue: "Vorläufer des Klaviers mit gezupften Saiten" },
  { word: "PARTITUR", clue: "Vollständige Notenschrift eines Musikstücks" },
  { word: "KAPELLMEISTER", clue: "Anderer Ausdruck für Dirigent" },
  { word: "MADRIGAL", clue: "Mehrstimmiges weltliches Vokalstück der Renaissance" },
  { word: "KANTATE", clue: "Mehrsätziges Vokalwerk mit Orchester" },
  { word: "REQUIEM", clue: "Musikalische Totenmesse" },
  { word: "OUVERTUERE", clue: "Instrumentale Einleitung einer Oper" },
  { word: "ARIE", clue: "Sologesangsstück in einer Oper" },
  { word: "CHOREOGRAFIE", clue: "Choreografische Gestaltung eines Tanzes" },
  { word: "BALLETT", clue: "Klassische Tanzkunstform" },
  { word: "PIROUETTE", clue: "Drehfigur im Ballett" },
  { word: "AQUARELL", clue: "Malerei mit wasserlöslichen Farben" },
  { word: "PERSPEKTIVE", clue: "Räumliche Darstellungstechnik in der Malerei" },
  { word: "SILHOUETTE", clue: "Einfarbiger Umriss einer Figur" },
  { word: "KARIKATUR", clue: "Übertrieben-satirische Bildzeichnung" },
  { word: "GRAFFITI", clue: "Sprühbild an Wänden im öffentlichen Raum" },
  { word: "AVANTGARDE", clue: "Kunstströmung, die neue Wege beschreitet" },
  { word: "KUBISMUS", clue: "Kunstrichtung mit geometrisch zerlegten Formen" },
  { word: "MINIMALISMUS", clue: "Kunststil der bewussten Reduktion" },
  { word: "PROTAGONIST", clue: "Hauptfigur einer Geschichte" },
  { word: "ANTAGONIST", clue: "Gegenspieler der Hauptfigur" },
  { word: "DRAMATURGIE", clue: "Lehre vom Aufbau eines Bühnenwerks" },
  { word: "MONOLOG", clue: "Sprechen einer einzelnen Figur allein" },
  { word: "DIALOG", clue: "Gespräch zwischen zwei oder mehr Figuren" },
  { word: "REZENSION", clue: "Kritische Besprechung eines Werkes" },
  { word: "BESTSELLER", clue: "Besonders erfolgreiches Buch" },
  { word: "PSEUDONYM", clue: "Angenommener Künstlername" },
  { word: "AUTOBIOGRAFIE", clue: "Selbst verfasste Lebensgeschichte" },
  { word: "MEMOIREN", clue: "Aufgezeichnete Lebenserinnerungen" },
  { word: "ANEKDOTE", clue: "Kurze, pointierte Erzählung" },
  { word: "FABEL", clue: "Lehrreiche Tiergeschichte" },
  { word: "MAERCHEN", clue: "Fantastische Erzählung mit Zauberwesen" },
  { word: "SAGE", clue: "Überlieferte Erzählung mit wahrem Kern" },
  { word: "EPOS", clue: "Langes erzählendes Versgedicht" },
  { word: "BALLADE", clue: "Erzählendes Gedicht mit dramatischem Inhalt" },
  { word: "HAIKU", clue: "Kurze japanische Gedichtform" },
  { word: "REIM", clue: "Klanggleichheit am Versende" },
  { word: "STROPHE", clue: "Abschnitt eines Gedichts" },
  { word: "PROSA", clue: "Nicht in Versform geschriebener Text" },
  { word: "ROMAN", clue: "Umfangreiches erzählendes Prosawerk" },
  { word: "NOVELLE", clue: "Kürzere erzählende Prosaform" },
  { word: "ESSAY", clue: "Kurze, meinungsbetonte Abhandlung" },
  { word: "GLOSSAR", clue: "Verzeichnis erklärter Fachbegriffe" },
  { word: "LEXIKON", clue: "Nachschlagewerk mit alphabetischer Ordnung" },
  { word: "ARCHIV", clue: "Sammlung historischer Dokumente" },
  { word: "INKUNABEL", clue: "Frühdruck aus der Zeit vor 1500" },
  { word: "KALLIGRAFIE", clue: "Kunst der schönen Handschrift" },
  { word: "TYPOGRAFIE", clue: "Gestaltungslehre gedruckter Schrift" },
  { word: "REDAKTEUR", clue: "Person, die journalistische Texte bearbeitet" },
  { word: "KORRESPONDENT", clue: "Auslandsberichterstatter einer Zeitung" },
  { word: "LEITARTIKEL", clue: "Meinungsbetonter Zeitungsartikel an prominenter Stelle" },
  { word: "SCHLAGZEILE", clue: "Auffällige Überschrift einer Nachricht" },
  { word: "PRESSEFREIHEIT", clue: "Recht auf unabhängige Berichterstattung" },
  { word: "DEMONSTRATION", clue: "Öffentlicher Protestzug" },
  { word: "REFERENDUM", clue: "Volksabstimmung über eine Sachfrage" },
  { word: "KOALITION", clue: "Bündnis mehrerer Parteien zur Regierungsbildung" },
  { word: "OPPOSITION", clue: "Parlamentarische Gegenkraft zur Regierung" },
  { word: "BUEROKRATIE", clue: "Verwaltungsapparat mit vielen Vorschriften" },
  { word: "SOUVERAENITAET", clue: "Höchste Staatsgewalt eines Landes" },
  { word: "NEUTRALITAET", clue: "Bündnisfreiheit in Konflikten" },
  { word: "EMBARGO", clue: "Handelsverbot gegen einen Staat" },
  { word: "SANKTION", clue: "Politische oder wirtschaftliche Strafmaßnahme" },
  { word: "DIPLOMATIE", clue: "Kunst der zwischenstaatlichen Verhandlung" },
  { word: "KONSULAT", clue: "Auslandsvertretung für Bürgerangelegenheiten" },
  { word: "VISUM", clue: "Einreiseerlaubnis für ein fremdes Land" },
  { word: "KONJUNKTUR", clue: "Wirtschaftliche Auf- und Abschwungphase" },
  { word: "ARBEITSLOSIGKEIT", clue: "Fehlen bezahlter Beschäftigung" },
  { word: "GEWERKSCHAFT", clue: "Interessenvertretung der Arbeitnehmer" },
  { word: "TARIFVERTRAG", clue: "Vereinbarung über Löhne und Arbeitsbedingungen" },
  { word: "DOMINO", clue: "Spiel mit Steinen und passenden Punktzahlen" },
  { word: "SUDOKU", clue: "Zahlenrätsel mit neun mal neun Feldern" },
  { word: "SCRABBLE", clue: "Brettspiel mit Buchstabensteinen" },
  { word: "BACKGAMMON", clue: "Altes Würfel-Brettspiel für zwei Personen" },
  { word: "TAROT", clue: "Kartendeck zur Wahrsagung" },
  { word: "ROULETTE", clue: "Glücksspiel mit rotierender Scheibe" },
  { word: "MARIONETTE", clue: "An Fäden geführte Gliederpuppe" },
  { word: "ILLUSIONIST", clue: "Künstler, der Zaubertricks vorführt" },
  { word: "AKROBAT", clue: "Künstler mit außergewöhnlicher Körperbeherrschung" },
  { word: "PANTOMIME", clue: "Darstellende Kunst ohne Worte" },
  { word: "BAUCHREDNER", clue: "Künstler, der ohne Lippenbewegung spricht" },
];
