// German word bank for the crossword puzzle mode: classic (non-cryptic)
// clues, but pitched at a more challenging, adult general-knowledge level
// rather than simple object descriptions. Words avoid umlauts/ß for
// simpler grid handling; each entry is { word, clue }.

export const WORD_BANK = [
  { word: "BERLIN", clue: "Hauptstadt Deutschlands" },
  { word: "PARIS", clue: "Hauptstadt Frankreichs" },
  { word: "MADRID", clue: "Hauptstadt Spaniens" },
  { word: "CANBERRA", clue: "Hauptstadt Australiens" },
  { word: "OTTAWA", clue: "Hauptstadt Kanadas" },
  { word: "LISSABON", clue: "Hauptstadt Portugals" },
  { word: "ATHEN", clue: "Hauptstadt Griechenlands, Wiege der Demokratie" },
  { word: "KAIRO", clue: "Hauptstadt Ägyptens am Nil" },
  { word: "DONAU", clue: "Zweitlängster Fluss Europas" },
  { word: "RHEIN", clue: "Fluss, der durch Basel, Köln und Rotterdam fließt" },
  { word: "ALPEN", clue: "Höchstes Gebirge Europas" },
  { word: "SAHARA", clue: "Größte Wüste der Welt" },
  { word: "AMAZONAS", clue: "Wasserreichster Fluss der Erde" },
  { word: "EVEREST", clue: "Höchster Berg der Welt" },
  { word: "PAZIFIK", clue: "Größter Ozean der Erde" },
  { word: "ANTARKTIS", clue: "Kontinent rund um den Südpol" },
  { word: "GALAXIE", clue: "Riesige Ansammlung von Sternen im All" },
  { word: "PLANET", clue: "Himmelskörper, der einen Stern umkreist" },
  { word: "JUPITER", clue: "Größter Planet unseres Sonnensystems" },
  { word: "MERKUR", clue: "Sonnennächster Planet" },
  { word: "GALILEI", clue: "Astronom, der die Jupitermonde entdeckte" },
  { word: "EINSTEIN", clue: "Physiker der Relativitätstheorie" },
  { word: "NEWTON", clue: "Namensgeber des Gravitationsgesetzes" },
  { word: "DARWIN", clue: "Begründer der Evolutionstheorie" },
  { word: "MOZART", clue: "Salzburger Komponist der Klassik" },
  { word: "BEETHOVEN", clue: "Tauber Komponist der Neunten Sinfonie" },
  { word: "GOETHE", clue: "Dichter des Faust" },
  { word: "SCHILLER", clue: "Dichter von Wilhelm Tell" },
  { word: "KAFKA", clue: "Prager Autor der Verwandlung" },
  { word: "SHAKESPEARE", clue: "Englischer Dramatiker aus Stratford" },
  { word: "PICASSO", clue: "Maler des Kubismus aus Spanien" },
  { word: "GUTENBERG", clue: "Erfinder des Buchdrucks" },
  { word: "PHARAO", clue: "Herrschertitel im alten Ägypten" },
  { word: "PYRAMIDE", clue: "Grabbauwerk der Pharaonen" },
  { word: "GLADIATOR", clue: "Kämpfer in der römischen Arena" },
  { word: "KOLOSSEUM", clue: "Antikes Amphitheater in Rom" },
  { word: "LEGION", clue: "Militärische Einheit im alten Rom" },
  { word: "IMPERIUM", clue: "Großes Herrschaftsgebiet, etwa das römische" },
  { word: "REPUBLIK", clue: "Staatsform ohne Monarchen" },
  { word: "DEMOKRATIE", clue: "Herrschaftsform des Volkes" },
  { word: "REVOLUTION", clue: "Grundlegender politischer Umsturz" },
  { word: "DIPLOMAT", clue: "Vertreter eines Staates im Ausland" },
  { word: "VERFASSUNG", clue: "Grundgesetzliches Regelwerk eines Staates" },
  { word: "PARLAMENT", clue: "Gesetzgebende Volksvertretung" },
  { word: "KANZLERIN", clue: "Weibliche Regierungschefin in Deutschland" },
  { word: "MONARCHIE", clue: "Staatsform mit erblichem Oberhaupt" },
  { word: "ATOM", clue: "Kleinster Baustein der Materie" },
  { word: "MOLEKUEL", clue: "Verbindung mehrerer Atome" },
  { word: "ELEMENT", clue: "Grundstoff im Periodensystem" },
  { word: "SAUERSTOFF", clue: "Lebenswichtiges Gas zum Atmen" },
  { word: "WASSERSTOFF", clue: "Leichtestes chemisches Element" },
  { word: "KOHLENSTOFF", clue: "Element, aus dem Diamant besteht" },
  { word: "GRAVITATION", clue: "Kraft, die Dinge zu Boden zieht" },
  { word: "ENERGIE", clue: "Physikalische Fähigkeit, Arbeit zu verrichten" },
  { word: "MAGNET", clue: "Objekt, das Eisen anzieht" },
  { word: "VULKAN", clue: "Berg, der Lava ausstößt" },
  { word: "ERDBEBEN", clue: "Plötzliche Erschütterung der Erdkruste" },
  { word: "GLETSCHER", clue: "Langsam fließende Eismasse im Gebirge" },
  { word: "OASE", clue: "Fruchtbare Wasserstelle in der Wüste" },
  { word: "TUNDRA", clue: "Baumlose Kältesteppe im hohen Norden" },
  { word: "DSCHUNGEL", clue: "Dichter tropischer Regenwald" },
  { word: "SAVANNE", clue: "Grasland mit vereinzelten Bäumen in Afrika" },
  { word: "FJORD", clue: "Schmale Meeresbucht in Skandinavien" },
  { word: "GEYSIR", clue: "Heiße Quelle, die periodisch Wasser ausstößt" },
  { word: "MERIDIAN", clue: "Gedachter Längenkreis auf der Erdkugel" },
  { word: "KONTINENT", clue: "Großer zusammenhängender Erdteil" },
  { word: "HALBINSEL", clue: "Landstück, das nur an einer Seite ans Meer grenzt" },
  { word: "ARCHIPEL", clue: "Gruppe eng beieinanderliegender Inseln" },
  { word: "METROPOLE", clue: "Bedeutende Großstadt" },
  { word: "NOMADE", clue: "Mensch ohne festen Wohnsitz" },
  { word: "KARAWANE", clue: "Reisegruppe durch die Wüste, oft mit Kamelen" },
  { word: "KOLONIE", clue: "Von einer fremden Macht beherrschtes Gebiet" },
  { word: "MYTHOLOGIE", clue: "Sammlung von Göttersagen eines Volkes" },
  { word: "ORAKEL", clue: "Antike Weissagungsstätte, etwa in Delphi" },
  { word: "SPHINX", clue: "Mischwesen mit Löwenkörper und Menschenkopf" },
  { word: "ODYSSEE", clue: "Homers Epos über eine lange Irrfahrt" },
  { word: "ILIAS", clue: "Homers Epos über den Krieg um Troja" },
  { word: "TROJA", clue: "Antike Stadt, berühmt durch ein hölzernes Pferd" },
  { word: "OLYMP", clue: "Sitz der griechischen Götter" },
  { word: "ZEUS", clue: "Oberster Gott der griechischen Mythologie" },
  { word: "POSEIDON", clue: "Griechischer Gott des Meeres" },
  { word: "ATHENE", clue: "Griechische Göttin der Weisheit" },
  { word: "PROMETHEUS", clue: "Titan, der den Menschen das Feuer brachte" },
  { word: "LABYRINTH", clue: "Verwirrendes Wegesystem mit vielen Sackgassen" },
  { word: "ALCHEMIE", clue: "Mittelalterliche Vorstufe der Chemie" },
  { word: "TELESKOP", clue: "Optisches Gerät zur Himmelsbeobachtung" },
  { word: "MIKROSKOP", clue: "Gerät zur Vergrößerung kleinster Objekte" },
  { word: "KOMPASS", clue: "Navigationsgerät mit magnetischer Nadel" },
  { word: "SEXTANT", clue: "Historisches Gerät zur Standortbestimmung auf See" },
  { word: "PENDEL", clue: "Physikalisches Objekt, das gleichmäßig schwingt" },
  { word: "PRISMA", clue: "Optisches Element, das Licht in Farben zerlegt" },
  { word: "SPEKTRUM", clue: "Zerlegtes Farbband des Lichts" },
  { word: "GENOM", clue: "Gesamte Erbinformation eines Lebewesens" },
  { word: "BAKTERIUM", clue: "Einzelliger Mikroorganismus" },
  { word: "VIRUS", clue: "Winziger Krankheitserreger ohne eigenen Stoffwechsel" },
  { word: "IMMUNSYSTEM", clue: "Körpereigene Abwehr gegen Krankheiten" },
  { word: "OEKOSYSTEM", clue: "Lebensgemeinschaft aus Organismen und Umwelt" },
  { word: "SYMBIOSE", clue: "Enges Zusammenleben zweier Arten zum beiderseitigen Nutzen" },
  { word: "MIGRATION", clue: "Wanderung von Tieren oder Menschen" },
  { word: "EPIDEMIE", clue: "Zeitlich begrenzte Ausbreitung einer Krankheit" },
  { word: "PANDEMIE", clue: "Weltweite Ausbreitung einer Krankheit" },
  { word: "ANTIBIOTIKUM", clue: "Medikament gegen bakterielle Infektionen" },
  { word: "DIAGNOSE", clue: "Ärztliche Feststellung einer Krankheit" },
  { word: "CHIRURG", clue: "Arzt, der operiert" },
  { word: "PSYCHOLOGIE", clue: "Wissenschaft vom menschlichen Erleben und Verhalten" },
  { word: "PHILOSOPHIE", clue: "Wissenschaft von den Grundfragen des Seins" },
  { word: "SOKRATES", clue: "Griechischer Philosoph, Lehrer Platons" },
  { word: "PLATON", clue: "Philosoph, der die Ideenlehre begründete" },
  { word: "ARISTOTELES", clue: "Schüler Platons und Lehrer Alexanders des Großen" },
  { word: "KANT", clue: "Königsberger Philosoph der Aufklärung" },
  { word: "NIETZSCHE", clue: "Philosoph, der Also sprach Zarathustra schrieb" },
  { word: "UTOPIE", clue: "Idealvorstellung einer nicht existierenden Gesellschaft" },
  { word: "IDEOLOGIE", clue: "System politischer oder gesellschaftlicher Grundüberzeugungen" },
  { word: "ETHIK", clue: "Lehre vom moralisch richtigen Handeln" },
  { word: "PARADOXON", clue: "Scheinbar widersprüchliche, aber wahre Aussage" },
  { word: "METAPHER", clue: "Sprachliches Bild, das einen Begriff durch einen anderen ersetzt" },
  { word: "SONETT", clue: "Gedichtform mit vierzehn Zeilen" },
  { word: "TRAGOEDIE", clue: "Dramatisches Werk mit unglücklichem Ausgang" },
  { word: "KOMOEDIE", clue: "Heiteres Bühnenstück mit gutem Ausgang" },
  { word: "SATIRE", clue: "Literarische Form, die Missstände spöttisch bloßstellt" },
  { word: "ALLEGORIE", clue: "Bildliche Darstellung eines abstrakten Begriffs" },
  { word: "MANUSKRIPT", clue: "Handschriftlicher oder ungedruckter Text" },
  { word: "PLAGIAT", clue: "Unrechtmäßige Übernahme fremden geistigen Eigentums" },
  { word: "ZENSUR", clue: "Staatliche Kontrolle und Unterdrückung von Inhalten" },
  { word: "PROPAGANDA", clue: "Gezielte, oft einseitige Beeinflussung der Meinung" },
  { word: "SYMPHONIE", clue: "Mehrsätziges Orchesterwerk" },
  { word: "LIBRETTO", clue: "Textbuch einer Oper" },
  { word: "DIRIGENT", clue: "Leiter eines Orchesters" },
  { word: "VIRTUOSE", clue: "Meisterhafter Künstler seines Fachs" },
  { word: "RENAISSANCE", clue: "Kulturelle Wiedergeburt der Antike ab dem 14. Jahrhundert" },
  { word: "BAROCK", clue: "Üppiger Kunststil des 17. Jahrhunderts" },
  { word: "IMPRESSIONISMUS", clue: "Kunstrichtung, die flüchtige Lichteindrücke einfängt" },
  { word: "SURREALISMUS", clue: "Kunstrichtung des Traumhaften und Unwirklichen" },
  { word: "FRESKO", clue: "Wandmalerei auf frischem Kalkputz" },
  { word: "MOSAIK", clue: "Bild aus vielen kleinen, zusammengesetzten Steinchen" },
  { word: "SKULPTUR", clue: "Dreidimensionales Kunstwerk, oft aus Stein oder Bronze" },
  { word: "ARCHITEKT", clue: "Person, die Gebäude entwirft" },
  { word: "KATHEDRALE", clue: "Große bischöfliche Kirche" },
  { word: "MINARETT", clue: "Turm einer Moschee" },
  { word: "PAGODE", clue: "Mehrstöckiger Tempelturm in Ostasien" },
  { word: "KATAKOMBE", clue: "Unterirdische Grabanlage" },
  { word: "MAUSOLEUM", clue: "Prunkvolles Grabmal" },
  { word: "OBELISK", clue: "Hoher, spitz zulaufender Steinpfeiler" },
  { word: "HIEROGLYPHE", clue: "Bildzeichen der altägyptischen Schrift" },
  { word: "PAPYRUS", clue: "Beschreibstoff des alten Ägypten" },
  { word: "AMPHORE", clue: "Antikes Gefäß mit zwei Henkeln" },
  { word: "DYNASTIE", clue: "Herrscherfolge innerhalb einer Familie" },
  { word: "MONOPOL", clue: "Alleinherrschaft eines Anbieters über einen Markt" },
  { word: "INFLATION", clue: "Anhaltender Anstieg des allgemeinen Preisniveaus" },
  { word: "REZESSION", clue: "Wirtschaftlicher Abschwung" },
  { word: "BOERSE", clue: "Markt für den Handel mit Wertpapieren" },
  { word: "WAEHRUNG", clue: "Gesetzliches Zahlungsmittel eines Landes" },
  { word: "EXPORT", clue: "Ausfuhr von Waren ins Ausland" },
  { word: "GLOBALISIERUNG", clue: "Zunehmende weltweite Vernetzung von Wirtschaft und Kultur" },
  { word: "URBANISIERUNG", clue: "Zunehmende Verstädterung einer Gesellschaft" },
  { word: "DEMOGRAFIE", clue: "Wissenschaft von der Bevölkerungsstruktur" },
  { word: "ARCHAEOLOGE", clue: "Wissenschaftler, der Ausgrabungen erforscht" },
  { word: "METEOROLOGE", clue: "Wissenschaftler, der das Wetter erforscht" },
  { word: "ASTRONAUT", clue: "Person, die ins Weltall reist" },
  { word: "KOSMONAUT", clue: "Russische Bezeichnung für Raumfahrer" },
  { word: "SATELLIT", clue: "Künstlicher Himmelskörper im Erdorbit" },
  { word: "RAKETE", clue: "Fahrzeug zum Start ins Weltall" },
  { word: "ORBIT", clue: "Umlaufbahn eines Himmelskörpers" },
  { word: "SCHWERELOSIGKEIT", clue: "Zustand ohne spürbare Gravitation" },
];
